services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-compcube}
      POSTGRES_USER: ${POSTGRES_USER:-compcube}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-compcube}
    ports:
      - "5432:5342"
    volumes:
      - compcube-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    build: .
    restart: unless-stopped
    env_file: [.env]
    environment:
      PGCONNECTSTRING: postgres://${POSTGRES_USER:-compcube}:${POSTGRES_PASSWORD:-compcube}@postgres:5432/${POSTGRES_DB:-compcube}
    ports:
      - "${REST_PORT:-7198}:7198"
      - "${WS_PORT:-8008}:8008"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  compcube-postgres:
